apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-config
  namespace: meeting-system
data:
  # --- DATABASE ---
  DB_HOST: "192.168.23.11"
  DB_PORT: "6033"
  DB_NAME: "meeting"
  AUTH_DB_NAME: "auth"
  
  # --- FRONTEND ---
  FRONTEND_BASE_URL: "https://npd-meeting.co"
  FRONTEND_REDIRECT_URI: "https://npd-meeting.co/authorized"
  
  # --- OAUTH2 ---
  ISSUER_URL: "https://oauth-meeting.co"
  OAUTH_CLIENT_ID: "meeting-client"
  OAUTH_POSTMAN_REDIRECT: "https://oauth.pstmn.io/v1/callback"
  OAUTH_POST_LOGOUT_URIS: "https://npd-meeting.co,https://npd-meeting.co/login"
  CORS_ALLOWED_ORIGINS: "https://npd-meeting.co,https://api-meeting.co"

  # --- RABBITMQ ---
  RABBITMQ_HOST: "192.168.23.11"
  RABBITMQ_PORT: "5672"

---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-secret
  namespace: meeting-system
type: Opaque
stringData:
  DB_USER: "dtkien5"
  DB_PASSWORD: "Kien2005@gym"
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "nguyenlee24"
  OAUTH_CLIENT_SECRET: "secret"
  
  # RSA Keys: Phải nằm trên đúng 1 dòng và bọc trong ngoặc kép "" để Java Base64 Decoder không bị lỗi
  RSA_PRIVATE_KEY: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFKx60ynKYtZiD3VHmSaidmQPMTh9w8yLoLLIP0xPb1MEGS/novvrGmmIfRITGoyLJS9c/TFfzK5Qmnp9xPHZPQ7vJT9ElCZJqmLFFBceFIjMySInl+PVs1c9u21HFKRl0ehqWMW39MGRjvw/6KgwwGcurRVMzYTNrLhBkMqCTx66jamdeyfZnzAHXZWU/tpd+al0cHi1XUPsJsOShhX9/YVjsPB/gdAOjZOSrxycdTvfYr5XdVBINcPgs1x2pvr489e3TccsW6ljIefWarzpsdGvvhPGklpJO5qF8gGDWmV+4+4qSQQM/zt47dedW56FeuSpGryLYYmBVvOGsqVXNAgMBAAECggEAJqVQg/QoaQkzBymiq2YloBpFVc68N+nYHjTgg9yGCHEXknHi3n1MbxAEiodmFP8VyunMG1KN7JJOnBE8RDgrIlcu4AL+helt4unh2RsMY+pzqXfxW3ukMzxnR53CVcg7/ooOWwD+Q4GwM6LX8Vs7f1QXCQ9yAuCa8Pea6+DGe6BwAhvJbrlYGLCxu1wjsbaqp+QWTXO3v8rlYaB5mKq3l9tyVfIxRC9tdz2+6esGPy/VZeRYcj3bKMZ2f0zljgXDw6ds6y5MZ/qr3flXdFhmfijBjdbVoIF+kENkfAmFskLaJP1hP5HILYe4Ydtq0afPkuPivXiPGfuc70/9xeLEQQKBgQDMcXxmxmmUiurz2ln7xLFgADVCmVFG7gDplbGICf4DUHvkDpVU4i3xwlcMXKAGqMOZwi9eQgvrV1n7+otapLWvMm3dT10OSZmyPGCHfV1Yii9dQKjNxWSk1L5zvqzKMGUA6cXklhnlEpoji3Uuc8D0CGTx8Zjz3ZIsCOrq+C51IQKBgQD24/sa3JQaHf3p4r2bho1a/uKaWw+tu4640+O3KseP5s/PQbSPTEM6F8FiNzgaZwz+u3rChWI155dkq3owjUttVmr/E2g9K4743Jvl1dEiHUZohZQyUE99vT1HWhS45t0fVAbmWOHwV+BXSg8oSjPBipgQ9xW2t2YNo5VOvpffLQKBgF438uf+isvdVbh6KbwhAsnGbsU5mT6CE0OTLFUQndLzNZV9rw6Gijv/n1RgH5PSFQr4dhIPiCS2hg7dgXmNrPmH2SAEIlOiUcXVk3r9qJZUYM2uLd1fGinorbjz5/fqY7IPCpd1IYvzjbvR2nhE+mi8saDbAe1pcKMAnRsas3ZhAoGBAOo0105iFXS5ItguqiPRfmLmDFzVKYhrtjaLeyeVQ361PEmmUPznIZcIVgEv1N7nByLXAtto4QO10J5FNUK9puHv6sxSwr3Uhmp6DMH5Fc1A7DvXDAC2wtHLJUh8oc/N4dIISgtWIe93zW/A56QW0AY3zY26dzS/weYKWmc60qN5AoGBAKNKqW59Ym5RKdtih4C0oB8+DbA4u8+FZ8t4VRwyrlv5FtqyvCDXTQn0sluI8Sqd5STOx1ghQZy+wVxxiZ997Solr+JSzm7fwqJdM/uMw2N3CVTaVet8OTRvmuc9mKJ+7KdQ0v2LWJH9BGDVJmWzywQX4GuiKrYq0DG/P9sl4//p"
  RSA_PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxSsetMpymLWYg91R5kmonZkDzE4fcPMi6CyyD9MT29TBBkv56L76xppiH0SExqMiyUvXP0xX8yuUJp6fcTx2T0O7yU/RJQmSapixRQXHhSIzMkiJ5fj1bNXPbttRxSkZdHoaljFt/TBkY78P+ioMMBnLq0VTM2Ezay4QZDKgk8euo2pnXsn2Z8wB12VlP7aXfmpdHB4tV1D7CbDkoYV/f2FY7Dwf4HQDo2Tkq8cnHU732K+V3VQSDXD4LNcdqb6+PPXt03HLFupYyHn1mq86bHRr74TxpJaSTuahfIBg1plfuPuKkkEDP87eO3XnVuehXrkqRq8i2GJgVbzhrKlVzQIDAQAB"