apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-deployment
  namespace: meeting-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth-service
  template:
    metadata:
      labels:
        app: oauth-service
    spec:
      containers:
        - name: oauth-service
          image: gk123a/meeting-oauth2-service:v2.0.3-dev
          command: ["/bin/sh", "-c"]
          args:
            - |
              touch .env && 
              java -jar app.jar
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: oauth-config
            - secretRef:
                name: oauth-secret
          env:
            # SỬA Ở DÒNG NÀY:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://$(DB_HOST):$(DB_PORT)/$(AUTH_DB_NAME)?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8"
            
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: DB_PASSWORD
                  
            # Tiện tay thêm dòng này để chặn trước lỗi mất Cookie khi chạy qua Nginx HTTPS
            - name: SERVER_FORWARD_HEADERS_STRATEGY
              value: "framework"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"